package com.beamsuntory.amz.de.harmonization.arap

import com.beamsuntory.amz.de.commons.UtilsAmzDE
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{col, trim}

trait HarmonizationArapColumns {
  val utils: UtilsAmzDE

  val selCustomerReviewsColumns: Seq[Column] = Seq(
    col("asin"),
    col("parent_asin"),
    col("ean").cast("bigint"),
    col("upc").cast("bigint"),
    col("product_title"),
    col("brand"),
    col("subcategory"),
    col("category"),
    col("num_customer_reviews").cast("int"),
    col("num_customer_reviews_prior_period").cast("int"),
    col("num_customer_reviews_life_to_date").cast("int"),
    col("avg_customer_rating").cast("double"),
    col("avg_customer_rating_prior_period").cast("double"),
    col("avg_customer_rating_life_to_date").cast("double"),
    col("five_stars").cast("int"),
    col("four_stars").cast("int"),
    col("three_stars").cast("int"),
    col("two_stars").cast("int"),
    col("one_star").cast("int"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("end_date"),
    col("week"),
    col("year"),
    col("day"),
    col("week_amz")
  )

  val selInventoryHealthColumns: Seq[Column] = Seq(
    col("asin"),
    col("parent_asin"),
    col("ean").cast("bigint"),
    col("upc").cast("bigint"),
    col("product_title"),
    col("brand"),
    col("subcategory"),
    col("category"),
    col("net_received").cast("double"),
    col("net_received_units").cast("int"),
    col("sell_through_rate").cast("double"),
    col("open_purchase_order_quantity").cast("int"),
    col("sellable_on_hand_inventory").cast("double"),
    col("sellable_on_hand_inventory_trailing_30_day_avg").cast("double"),
    col("sellable_on_hand_units").cast("int"),
    col("unsellable_on_hand_inventory").cast("double"),
    col("unsellable_on_hand_inventory_trailing_30_day_avg").cast("double"),
    col("unsellable_on_hand_units").cast("int"),
    col("aged_90_plus_days_sellable_inventory").cast("double"),
    col("aged_90_plus_days_sellable_inventory_trailing_30_day_avg").cast("double"),
    col("aged_90_plus_days_sellable_units").cast("int"),
    col("unhealthy_inventory").cast("double"),
    col("unhealthy_inventory_trailing_30_day_avg").cast("double"),
    col("unhealthy_units").cast("int"),
    col("replenishment_category"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz")
  )

  val selForecastOrderedColumns: Seq[Column] = Seq(
    col("asin"),
    col("ean").cast("bigint"),
    col("upc").cast("bigint"),
    col("product_title"),
    col("brand"),
    col("subcategory"),
    col("category"),
    col("rep_oos").cast("double"),
    col("rep_oos_pct_total").cast("double"),
    col("rep_oos_prior_period").cast("double"),
    col("ordered_units").cast("int"),
    col("ordered_units_prior_period").cast("double"),
    col("unfilled_customer_ordered_units").cast("int"),
    col("available_inventory").cast("int"),
    col("available_inventory_prior_period").cast("double"),
    col("weeks_on_hand").cast("int"),
    col("open_purchase_order_quantity").cast("int"),
    col("open_purchase_order_quantity_prior_period").cast("double"),
    col("receive_fill_rate_pct").cast("double"),
    col("replenishment_category"),
    col("week_model").cast("int"),
    col("value_model").cast("int"),
    col("model"),
    col("start_date"),
    col("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("month"),
    col("quarter"),
    col("week_amz")
  )

  val selForecastShippedColumns: Seq[Column] = Seq(
    col("asin"),
    col("parent_asin"),
    col("ean").cast("bigint"),
    col("upc").cast("bigint"),
    col("product_title"),
    col("brand"),
    col("subcategory"),
    col("category"),
    col("rep_oos").cast("double"),
    col("rep_oos_pct_total").cast("double"),
    col("rep_oos_prior_period").cast("double"),
    col("shipped_units").cast("int"),
    col("shipped_units_prior_period").cast("double"),
    col("unfilled_customer_ordered_units").cast("int"),
    col("available_inventory").cast("int"),
    col("available_inventory_prior_period").cast("double"),
    col("weeks_on_hand").cast("int"),
    col("open_purchase_order_quantity").cast("int"),
    col("open_purchase_order_quantity_prior_period").cast("double"),
    col("receive_fill_rate_pct").cast("double"),
    col("replenishment_category"),
    col("week_model").cast("int"),
    col("value_model").cast("int"),
    col("model"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz")
  )

  val selSalesOrderedColumns: Seq[Column] = Seq(
    trim(col("asin")).as("asin"),
    col("ean").cast("bigint"),
    col("upc").cast("bigint"),
    col("parent_asin"),
    trim(col("product_title")).as("product_title"),
    col("brand"),
    col("subcategory"),
    col("category"),
    col("ordered_revenue").cast("double"),
    col("ordered_revenue_percentage_total").cast("double").as("ordered_revenue_pct_total"),
    col("ordered_revenue_prior_period").cast("double").as("ordered_revenue_pct_prior_period"),
    col("ordered_revenue_last_year").cast("double").as("ordered_revenue_pct_last_year"),
    col("ordered_units").cast("int"),
    col("ordered_units_percentage_total").cast("double").as("ordered_units_pct_total"),
    col("ordered_units_prior_period").cast("double").as("ordered_units_pct_prior_period"),
    col("ordered_units_last_year").cast("double").as("ordered_units_pct_last_year"),
    col("subcategory_sales_rank").cast("int").as("subcategory_sales_rank_ordered"),
    col("subcategory_better_worse").cast("double").as("subcategory_better_worse_ordered"),
    col("average_sales_price").cast("double").as("avg_sales_price_ordered"),
    col("average_sales_price_prior_period").cast("double").as("avg_sales_price_pct_prior_period_ordered"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz")
  )

  val selOrderedLyColumns: Seq[Column] = Seq(
    col("ordered_units").as("ordered_units_ly"),
    col("ordered_revenue").as("ordered_revenue_ly"),
    col("asin"),
    col("day"),
    col("month"),
    col("year")
  )

  val selSalesShippedColumns: Seq[Column] = Seq(
    trim(col("asin")).as("asin"),
    //col("ean").cast("bigint"),
    //col("upc").cast("bigint"),
    //col("parent_asin"),
    //trim(col("product_title")).as("product_title"),
    col("shipped_revenue").cast("double"),
    col("shipped_revenue_percentage_total").cast("double").as("shipped_revenue_pct_total"),
    col("shipped_revenue_priod_period").cast("double").as("shipped_revenue_pct_prior_period"),
    col("shipped_revenue_last_year").cast("double").as("shipped_revenue_pct_last_year"),
    col("shipped_units").cast("int"),
    col("shipped_units_percentage_total").cast("double").as("shipped_units_pct_total"),
    col("shipped_units_priod_period").cast("double").as("shipped_units_pct_prior_period"),
    col("shipped_units_last_year").cast("double").as("shipped_units_pct_last_year"),
    col("customer_returns").cast("int"),
    col("free_replacements").cast("int"),
    col("subcategory_sales_rank").cast("int").as("subcategory_sales_rank_shipped"),
    col("subcategory_better_worse").cast("double").as("subcategory_better_worse_shipped"),
    col("average_sales_price").cast("double").as("avg_sales_price_shipped"),
    col("average_sales_price_prior_period").cast("double").as("avg_sales_price_pct_prior_period_shipped"),
    col("change_in_gv_prior_period").cast("double").as("change_gv_pct_prior_period"),
    col("change_in_gv_last_year").cast("double").as("change_gv_pct_last_year"),
    col("rep_oos").cast("double").as("rep_oss_pct"),
    col("rep_oos_percentage_total").cast("double").as("rep_oss_pct_total"),
    col("rep_oos_prior_period").cast("double").as("rep_oss_pct_prior_period"),
    col("lbb").cast("double").as("lbb_pct"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz")
  )

  val selSalesDiagnosticUnionColumns: Seq[Column] = Seq(
    col("asin"),
    utils.chooseField("ean"),
    utils.chooseField("upc"),
    utils.chooseField("parent_asin"),
    utils.chooseField("product_title"),
    col("brand"),
    col("subcategory"),
    col("category"),
    col("ordered_revenue"),
    col("ordered_revenue_pct_total"),
    col("ordered_revenue_pct_prior_period"),
    col("ordered_revenue_pct_last_year"),
    col("ordered_units"),
    col("ordered_units_pct_total"),
    col("ordered_units_pct_prior_period"),
    col("ordered_units_pct_last_year"),
    col("ordered_revenue_last_year"),
    col("ordered_units_last_year"),
    col("ordered_revenue_prior_period"),
    col("ordered_units_prior_period"),
    col("ordered_units_inc_last_year"),
    col("ordered_revenue_inc_last_year"),
    col("ordered_units_inc_prior_period"),
    col("ordered_revenue_inc_prior_period"),
    col("subcategory_sales_rank_ordered"),
    col("subcategory_better_worse_ordered"),
    col("avg_sales_price_ordered"),
    col("avg_sales_price_pct_prior_period_ordered"),
    col("shipped_revenue"),
    col("shipped_revenue_pct_total"),
    col("shipped_revenue_pct_prior_period"),
    col("shipped_revenue_pct_last_year"),
    col("shipped_units"),
    col("shipped_units_pct_total"),
    col("shipped_units_pct_prior_period"),
    col("shipped_units_pct_last_year"),
    col("shipped_revenue_last_year"),
    col("shipped_units_last_year"),
    col("shipped_revenue_prior_period"),
    col("shipped_units_prior_period"),
    col("shipped_units_inc_last_year"),
    col("shipped_revenue_inc_last_year"),
    col("shipped_units_inc_prior_period"),
    col("shipped_revenue_inc_prior_period"),
    col("customer_returns"),
    col("free_replacements"),
    col("subcategory_sales_rank_shipped"),
    col("subcategory_better_worse_shipped"),
    col("avg_sales_price_shipped"),
    col("avg_sales_price_pct_prior_period_shipped"),
    col("change_gv_pct_prior_period"),
    col("change_gv_pct_last_year"),
    col("rep_oss_pct"),
    col("rep_oss_pct_total"),
    col("rep_oss_pct_prior_period"),
    col("lbb_pct"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz")
  )

  val selSalesDiagnosticUnionSourcingColumns: Seq[Column] = Seq(
    col("asin"),
    utils.chooseField("ean"),
    utils.chooseField("upc"),
    utils.chooseField("parent_asin"),
    utils.chooseField("product_title"),
    col("brand"),
    col("subcategory"),
    col("category"),
    col("ordered_revenue"),
    col("ordered_revenue_pct_total"),
    col("ordered_revenue_pct_prior_period"),
    col("ordered_revenue_pct_last_year"),
    col("ordered_units"),
    col("ordered_units_pct_total"),
    col("ordered_units_pct_prior_period"),
    col("ordered_units_pct_last_year"),
    col("ordered_revenue_last_year"),
    col("ordered_units_last_year"),
    col("ordered_revenue_prior_period"),
    col("ordered_units_prior_period"),
    col("ordered_units_inc_last_year"),
    col("ordered_revenue_inc_last_year"),
    col("ordered_units_inc_prior_period"),
    col("ordered_revenue_inc_prior_period"),
    col("subcategory_sales_rank_ordered"),
    col("subcategory_better_worse_ordered"),
    col("avg_sales_price_ordered"),
    col("avg_sales_price_pct_prior_period_ordered"),
    col("shipped_revenue"),
    col("shipped_revenue_pct_total"),
    col("shipped_revenue_pct_prior_period"),
    col("shipped_revenue_pct_last_year"),
    col("shipped_units"),
    col("shipped_units_pct_total"),
    col("shipped_units_pct_prior_period"),
    col("shipped_units_pct_last_year"),
    col("shipped_revenue_last_year"),
    col("shipped_units_last_year"),
    col("shipped_revenue_prior_period"),
    col("shipped_units_prior_period"),
    col("shipped_units_inc_last_year"),
    col("shipped_revenue_inc_last_year"),
    col("shipped_units_inc_prior_period"),
    col("shipped_revenue_inc_prior_period"),
    col("customer_returns"),
    col("free_replacements"),
    col("shipped_revenue_sourcing"),
    col("shipped_revenue_pct_total_sourcing"),
    col("shipped_revenue_pct_prior_period_sourcing"),
    col("shipped_revenue_pct_last_year_sourcing"),
    col("shipped_units_sourcing"),
    col("shipped_units_pct_total_sourcing"),
    col("shipped_units_pct_prior_period_sourcing"),
    col("shipped_units_pct_last_year_sourcing"),
    col("shipped_revenue_sourcing_last_year"),
    col("shipped_units_sourcing_last_year"),
    col("customer_returns_sourcing"),
    col("free_replacements_sourcing"),
    col("avg_sales_price_shipped_sourcing"),
    col("avg_sales_price_pct_prior_period_shipped_sourcing"),
    col("subcategory_sales_rank_shipped"),
    col("subcategory_better_worse_shipped"),
    col("avg_sales_price_shipped"),
    col("avg_sales_price_pct_prior_period_shipped"),
    col("change_gv_pct_prior_period"),
    col("change_gv_pct_last_year"),
    col("rep_oss_pct"),
    col("rep_oss_pct_total"),
    col("rep_oss_pct_prior_period"),
    col("lbb_pct"),
    col("start_date"),
    col("month"),
    col("quarter"),
    utils.chooseField("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz"),
    col("distributor_sourcing"),
    col("shipped_revenue_last_year_aux"),
    col("shipped_units_last_year_aux")
  )

  val selSalesSourcingColumns: Seq[Column] = Seq(
    trim(col("asin")).as("asin"),
    col("ean").cast("bigint"),
    col("upc").cast("bigint"),
    col("parent_asin"),
    trim(col("product_title")).as("product_title"),
    col("shipped_revenue_sourcing").cast("double"),
    col("shipped_revenue_percentage_total_sourcing").cast("double").as("shipped_revenue_pct_total_sourcing"),
    col("shipped_revenue_priod_period_sourcing").cast("double").as("shipped_revenue_pct_prior_period_sourcing"),
    col("shipped_revenue_last_year_sourcing").cast("double").as("shipped_revenue_pct_last_year_sourcing"),
    col("shipped_units_sourcing").cast("int"),
    col("shipped_units_percentage_total_sourcing").cast("double").as("shipped_units_pct_total_sourcing"),
    col("shipped_units_priod_period_sourcing").cast("double").as("shipped_units_pct_prior_period_sourcing"),
    col("shipped_units_last_year_sourcing").cast("double").as("shipped_units_pct_last_year_sourcing"),
    col("customer_returns_sourcing").cast("int"),
    col("free_replacements_sourcing").cast("int"),
    col("average_sales_price_sourcing").cast("double").as("avg_sales_price_shipped_sourcing"),
    col("average_sales_price_prior_period_sourcing").cast("double").as("avg_sales_price_pct_prior_period_shipped_sourcing"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz")
  )


  val selShippedSourcingLyColumns: Seq[Column] = Seq(
    col("shipped_units_sourcing").as("shipped_units_sourcing_ly"),
    col("shipped_revenue_sourcing").as("shipped_revenue_sourcing_ly"),
    col("asin"),
    col("day"),
    col("month"),
    col("year")
  )

  val selSalesDiagnosticLyCalculated: Seq[Column] = Seq(
    col("asin"),
    col("ean").cast("bigint"),
    col("upc").cast("bigint"),
    col("parent_asin"),
    col("product_title"),
    col("brand"),
    col("subcategory"),
    col("category"),
    col("ordered_revenue_last_year").cast("double").as("ordered_revenue"),
    col("ordered_units_last_year").cast("int").as("ordered_units"),
    col("shipped_revenue_last_year").cast("double").as("shipped_revenue"),
    col("shipped_units_last_year").cast("int").as("shipped_units"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz")
  )

  val selSalesDiagnosticLy: Seq[Column] = Seq(
    col("asin"),
    col("ean"),
    col("ordered_revenue").cast("double").as("ordered_revenue_last_year_aux"),
    col("ordered_units").cast("int").as("ordered_units_last_year_aux"),
    col("shipped_revenue").cast("double").as("shipped_revenue_last_year_aux"),
    col("shipped_units").cast("int").as("shipped_units_last_year_aux"),
    col("month"),
    col("quarter"),
    col("year"),
    col("day")
  )

  val selSalesDiagnosticSourcingLyCalculated: Seq[Column] = Seq(
    col("asin"),
    col("shipped_revenue_sourcing_last_year").cast("double").as("shipped_revenue_sourcing"),
    col("shipped_units_sourcing_last_year").cast("int").as("shipped_units_sourcing"),
    col("distributor_sourcing"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz")
  )

  val selSalesDiagnosticSourcingLy: Seq[Column] = Seq(
    col("asin"),
    col("shipped_revenue_sourcing").cast("double").as("shipped_revenue_sourcing_last_year_aux"),
    col("shipped_units_sourcing").cast("int").as("shipped_units_sourcing_last_year_aux"),
    col("month"),
    col("quarter"),
    col("year"),
    col("day")
  )

  val selGeographicSales: Seq[Column] = Seq(
    col("asin"),
    col("parent_asin"),
    col("ean").cast("bigint"),
    col("upc").cast("bigint"),
    col("product_title"),
    col("brand"),
    col("subcategory"),
    col("category"),
    col("country"),
    col("state"),
    col("city"),
    col("plz"),
    col("shipped_revenue").cast("double"),
    col("shipped_revenue_percentage_total").cast("double").as("shipped_revenue_pct_total"),
    col("shipped_revenue_priod_period").cast("double").as("shipped_revenue_pct_prior_period"),
    col("shipped_revenue_last_year").cast("double").as("shipped_revenue_pct_last_year"),
    col("shipped_units").cast("int"),
    col("shipped_units_percentage_total").cast("double").as("shipped_units_pct_total"),
    col("shipped_units_priod_period").cast("double").as("shipped_units_pct_prior_period"),
    col("shipped_units_last_year").cast("double").as("shipped_units_pct_last_year"),
    col("average_sales_price").cast("double"),
    col("average_sales_price_prior_period").cast("double").cast("double"),
    col("average_sales_price_last_year").cast("double"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("end_date"),
    col("year"),
    col("day"),
    col("week"),
    col("week_amz")
  )

  val selSalesInsightsColumns: Seq[Column] = Seq(
    col("gsi.asin") ,
    col("gsi.parent_asin") ,
    col("gsi.ean") ,
    col("gsi.upc") ,
    col("gsi.product_title") ,
    col("gsi.brand") ,
    col("gsi.subcategory") ,
    col("gsi.category") ,
    col("gsi.country") ,
    col("gsi.state") ,
    col("gsi.city") ,
    col("gsi.plz"),
    col("gsi.shipped_revenue" ),
    col("gsi.shipped_revenue_percentage_total" ),
    col("gsi.shipped_revenue_priod_period" ),
    col("gsi.shipped_revenue_last_year" ),
    col("gsi.shipped_units" ),
    col("gsi.shipped_units_percentage_total" ),
    col("gsi.shipped_units_priod_period" ),
    col("gsi.shipped_units_last_year" ),
    col("gsi.average_sales_price" ),
    col("gsi.average_sales_price_prior_period" ),
    col("gsi.average_sales_price_last_year" ),
    col("gsi.start_date" ),
    col("gsi.month"),
    col("gsi.quarter"),
    col("gsi.end_date" ),
    col("gsi.year"),
    col("gsi.day"),
    col("gsi.week" ),
    col("gsi.week_amz" ),
    col("gsi.key_words" )
  )

  val selItemComparisonColumns: Seq[Column] = Seq(
    col("asin"),
    col("product_title"),
    col("compared_asin"),
    col("compared_product_title"),
    col("compared_pct").cast("double"),
    col("type"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("year"),
    col("day"),
    col("end_date")
  )

  val selAlternatePurchaseColumns: Seq[Column] = Seq(
    col("asin"),
    col("product_title"),
    col("purchase_asin").as("alternate_purchase_asin"),
    col("purchase_product_title").as("alternate_purchase_product_title"),
    col("purchase_percentage").as("alternate_purchase_pct").cast("double"),
    col("type"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("year"),
    col("day"),
    col("end_date")
  )

  val selAmzTermsColumns: Seq[Column] = Seq(
    col("search_term"),
    col("department"),
    col("search_frequency_rank").cast("int"),
    col("clicked_asin"),
    col("product_title").as("clicked_product_title"),
    col("click_share").cast("double"),
    col("conversion_share").cast("double"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("year"),
    col("day"),
    col("end_date")
  )

  val selMarketBasketAnalysisColumns: Seq[Column] = Seq(
    col("asin"),
    col("product_title"),
    col("purchased_asin"),
    col("purchased_title"),
    col("combination_pct").cast("double"),
    col("type"),
    col("start_date"),
    col("month"),
    col("quarter"),
    col("year"),
    col("day"),
    col("end_date")
  )

}
